from __future__ import annotations


class SeedItineraryProvider:
    def generate_itinerary(self, *, messages, rag_hits) -> dict:
        user_message = messages[-1].content if messages else "Travel plan"
        return {
            "trip_summary": f"Seed itinerary for: {user_message}",
            "timezone": "UTC",
            "currency": "USD",
            "assumptions": ["Generated by deterministic seed provider."],
            "days": [{"date": "2026-07-01", "city": "", "items": []}],
            "budget_summary": {"total": 0},
            "rag_citations": [],
        }
